name: C CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install-readline
      environment:
        ACCEPT_EULA: 'y'
      run: |
        sudo apt-get update  -y
        sudo ACCEPT_EULA=Y apt-get install -y build-essential libreadline-dev  libgtk-3-dev
        sudo ACCEPT_EULA=Y apt-get upgrade -y
    - name: make
      run: make
    - name: make-gui
      run: make gui
