name: C CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install-readline
      run: sudo apt-get install lib32readline7 libreadline-dev
    - name: make
      run: make
